# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# extract_arcpy.py
# Created on: 2015-04-02 11:05:03.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")


# Local variables:
C1_agua_bin_float_MW0300m_tif = "c1\\C1_agua_bin_float_MW0300m.tif"
v101_lotes_sir_buffer_50m_dissolv = "101_lotes_sir_buffer_50m_dissolv"
teste_tif = "E:\\data_2015\\___john\\Sidnei_parte2\\Vars_c4_exctratc_tif\\teste.tif"

# Process: Extract by Mask
arcpy.gp.ExtractByMask_sa(C1_agua_bin_float_MW0300m_tif, v101_lotes_sir_buffer_50m_dissolv, teste_tif)

